[project]
name = "job-app"
version = "0.1.0"
description = ""
authors = [
    {name = "Anna",email = "ankin0105@yandex.ru"}
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
]
[tool.poetry]
package-mode = false

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.group.dev.dependencies]
pytest = "8.3.3"
pytest-cov = "5.0.0"
requests-mock = "1.12.1"
pytest-mock = "3.14.0"

